# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "The Klog"

# A description of your site for social meta tag, search engines, and feed.xml
description: "The Klog - Krystof Litomisky's personal website and blog"

# Tagline near the site title
tagline: "From Krystof with Love"

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://krystofl.github.io"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Archives
  url: /tags/
- text: Contact
  url: /contact/

# The shortname for your Disqus site to enable comments.
disqus: the-klog

# Author information - author info at the bottom of the post
author_name: "Krystof Litomisky"
author_bio: "Krystof is an engineer, adventurer, and all-around good guy. He is currently based in Los Angeles, California."
#author_url:  "https://krystofl.github.io"
author_location: "Los Angeles, California"
author_image: /images/krystof-headshot.jpg

# Sidebar banner
#banner_url: "https://krystof.litomisky.com/about/"
banner_image: http://krystof.litomisky.com/klog-assets/images/krystof-sidebar.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
#mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
#mailchimp_url: "404.html"

# Social links in the site footer
twitter_username: "theKrystof"
#facebook_username: ""
github_username: "krystofl"
#codepen_username: ""
#dribbble_uername: ""
#medium_username: ""
instagram_username: "willingthrope"
#pinterest_username: ""
linkedin_username: "krystof-litomisky"
#weibo_username: ""

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false

timezone: America/Los_Angeles

#post_images_root: http://litomisky.com/klog-jekyll/img/posts
post_images_root: http://krystof.litomisky.com/klog-assets/images/posts
